version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    ports: 
        - '3306:3306'
    volumes:
        - ./data:/var/lib/mysql
        - ./artifacts/init_db:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=db
        - MYSQL_USER=app
        - MYSQL_PASSWORD=pass
